config/routes.rb
Rails.application.routes.draw do
   root to: "users#index"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :albums
resources :users, only: [:index]  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
	mount_uploaders :images, ImageUploader
	serialize :images
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    after_create :create_tenant

    private
    def create_tenant
    	Apartment::Tenant.create(subdomain)
    end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
	def index
		@picture = Picture.all
	end
	def new
		@picture = Picture.new
	end
	def create
		@picture=Picture.new(active_params)
		if @picture.save
			redirect_to album_path(@picture) , notice: "Successfully created new Picture" 
		else
			render :new
		end
	end

	def show
			@picture = Picture.find(params[:id])
	end

	private
		def active_params
			params.require(:album).permit(:name, :Description, {images: []})
		end
		def set_id
			@picture = Picture.find(params[:id])
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?


 protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:subdomain])
  end
  
def after_sign_in_path_for(user)
	albums_path
end
def after_sign_out_path_for(user)
	users_path
end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
	end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/index.html.erb
<div class="row">
	<% @picture.each do |pic|%>
		
		<div class="col-md-4" style="border: outset;">
		<h1><%= pic.name %></h1>
		<br>
		<h3><%= pic.Description %></h3>
		<br>
		<br>
	</div>
	<%end%>
</div>

app/views/albums/new.html.erb
<div class="container text_color">
	<div class="row">
		<div class="col-md-4">
		</div>
		<div class="col-md-4">
			<%= form_for :album, url: albums_path do |f| %>

				<div class="form-group ">
					<label for="exampleInputEmail1">
						NAME 
					</label>
					<%= f.text_field :name, autofocus: true, autocomplete: "name" ,class: "form-control"%>
				<div class="form-group">
					 
					<label for="exampleInputPassword1">
						Description
					</label>
					<%= f.text_field :Description, autofocus: true, autocomplete: "name" ,class: "form-control"%>
				</div>
				<div class="form-group">
					 
					<label for="exampleInputFile">
						File input
					</label>
					<%= f.file_field :images, multiple: true %>
					<p class="help-block">
						Example block-level help text here.
					</p>
				</div>
				<div class="checkbox">
					 
					<label>
						<input type="checkbox" /> Check me out
					</label>
				</div> 
				<button type="submit" class="btn btn-default">
					Submit
				</button>
			<%end%>
		</div>
		<div class="col-md-4">
		</div>
	</div>
</div>

app/views/albums/show.html.erb
<h1 style="text-align: center"><%= @picture.name%></h1>
<h3 ><%= @picture.Description%></h3>
<% @picture.images.each do |image|%>
<div class="col-md-4">
<%= image_tag(image.url, class: "size") %>
</div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Album</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <style> 
#myDIV {
    width: 100%;
    height: 100%;
    background: red;
    -webkit-animation: mymove 5s infinite; /* Chrome, Safari, Opera */
    animation: mymove 5s infinite;
}

/* Chrome, Safari, Opera */
@-webkit-keyframes mymove {
    from {background-image: url(https://static.pexels.com/photos/7919/pexels-photo.jpg);}
    to {background-image: url(https://static.pexels.com/photos/36487/above-adventure-aerial-air.jpg);}
}

/* Standard syntax */
from {background-image: url(https://static.pexels.com/photos/36487/above-adventure-aerial-air.jpg);}
    to {background-image: url(https://static.pexels.com/photos/7919/pexels-photo.jpg);}
</style>
  </head>

  <body id="myDIV">
    
      <div class="container">
        <div class="row">
          <div class="table-row">
            <div class="container">
            <div class="nav nav-tabs navbar-fixed-top nav_height">

              <li>
                <a href="#" class="nav_height">Home</a>
              </li>
              <li>
                <a href="#", class="nav_height">Profile</a>
              </li>
                <li class="dropdown pull-right">
              <%if current_user%>
                   <a href="#" data-toggle="dropdown" class="dropdown-toggle nav_height"><%= current_user.subdomain%><strong class="caret"></strong></a>
                <ul class="dropdown-menu">
                  <li>
                    <a href="<%=edit_user_registration_path%>">Edit account</a>
                  </li>
                  <li>
                    <a href="#">Something else here</a>
                  </li>
                  <li class="divider">
                  </li>
                  
                    <li>
                      <a href="<%=destroy_user_session_path%>", data-method="delete"><b>SignOut</b></a>
                    </li>
                 </ul> 
              <%else%>
                 
                  <ul class="dropdown-menu">
                    <li>
                      <a href="<%=new_user_session_path%>"><b>Log In</b></a>
                    </li>
                 </ul> 
              <%end%>
                <%if current_user%>
                <li class="pull-right">
                <a href="<%=new_album_path%>", class="nav_height">New Album</a>
              </li>
                <%else%>
                <li class="pull-right">
                <a href="<%=new_user_session_path%>", class="nav_height">Login</a>
              </li>
              <%end%>
              </li>
            </div>
          
        </div>
      </div>
      </div> 
      </div>   
      <%if notice.present? %>
     <div class="container">
          <div class="col-md-12">
            <nav class="nav nav-tabs notice_alert">
  	     <p class="notice"><%= notice %></p>
         </nav>
     </div>
         <%elsif alert.present? %>
         <div class="container-fluid">
          <div class="col-md-12">
            <nav class="nav nav-tabs notice_alert">
         <p class="alert"><%= alert %></p>
       </nav>
     </div>
     <%end%>
     <br>
     <br>
     <div class="container" style="margin-top: 70px">
          
          <%= yield %>
    </div>
  </body>
</html>

app/views/users/index.html.erb
<div class="container">
  <h2>Users with Subdomains</h2>
    <table class="table table-striped">
    <thead>
      <tr>
        <th>Serial no.</th>
        <th>Email</th>
        <th>Subdomain</th>
      </tr>
    </thead>
    <tbody>
      <%User.all.each do |user|%>  <tr>
          <td><%= user.id%></td>
          <td><%=user.email%></td>
          <td><%= user.subdomain%></td>
        </tr>
      <%end%>
    </tbody>
  </table>
</div>